# Generated by Django 6.0 on 2026-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inflow',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
